### ISSUE TITLE
How to improve box orientation?

### ISSUE THREAD

**Issue by VRichardJP** [LidarPerception/object_builders_lib#5]
First thanks a lot for sharing your code.

I am testing your bounding box generator in autoware.ai:
I am using a lidar based clustering algorithm to generate point clusters, which I feed to your object builder. I then convert the output objects into a jsk_recognition_msgs::BoundingBox so I can visualize the result in Rviz.

The result looks like this:
![Screenshot from 2020-06-18 17-49-07](https://user-images.githubusercontent.com/18645627/85000434-5c951280-b18d-11ea-8e6b-f6ef2a131459.png)

I think I am using your library correctly as the 3d boxes look rather nice. However, I notice some boxes orientation is not always great. For example in the image above, you can see the few cars on the right side of the road are not properly oriented (boxes should be straight).

Do you know any way to mitigate this issue?

Thanks

**Comment by Durant35** [comment]
Have seen https://www.youtube.com/watch?v=ZGzwdzMygLI&t=0s&list=LLbz4mTfvxwOQQQwDGaXf19A&index=13, maybe 2 years ago, but sorry, do not have time to implement it, how about reading this paper https://ieeexplore.ieee.org/document/8500692 for some ideas?

**Comment by VRichardJP** [comment]
Thanks for the lead. I will try to dig this.

**Comment by VRichardJP** [comment]
I ended up using shape estimator from [AutowareArchitectureProposal](https://github.com/tier4/AutowareArchitectureProposal)

Bounding box generation can be found here:
https://github.com/tier4/autoware.iv.universe/tree/master/perception/object_recognition/detection/shape_estimation

It works rather good.
